Description of hit_error
Home > hit > hit_error.m
hit_error
PURPOSE
HIT_ERROR: Initializes the HIT toolbox if not already done
SYNOPSIS
function hit_error
DESCRIPTION
HIT_ERROR: Initializes the HIT toolbox if not already done
 ---------------------------------------------------------------------------
 DESCRIPTION
 ---------------------------------------------------------------------------
 Checks if the internal variables idpar and plotpar are defined in the MATLAB(R)
 workspace. If not, the HIT toolbox is initialized.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
hit_check_inliers HIT_CHECK_INLIERS Remove modes, if necessary, from a list of inliers
hit_compute_cont_modes HIT_COMPUTE_CONT_MODES Estimate the mode PVs in continuous PWA models
hit_create_LDs HIT_CREATE_LDS Create Local Datasets (LDs)
hit_estimate_cs HIT_ESTIMATE_CS Estimate the best mode number and/or the best size of LDs within a given range
hit_plotpar_check HIT_PLOTPAR_CHECK Check if the cell array of fields lfields in plotpar is well defined
hit_regression HIT_REGRESSION Main function for PWA regression.