Description of hit_regression
Home > hit > hit_regression.m
hit_regression
PURPOSE
HIT_REGRESSION Main function for PWA regression.
SYNOPSIS
function [idmodes,F,xi,LDs,inliers]=hit_regression(Xid,yid)
DESCRIPTION
HIT_REGRESSION Main function for PWA regression.
 -------------------------------------------------------------------------
 DESCRIPTION
 -------------------------------------------------------------------------
 [idmodes,F,xi,LDs,inliers]=hit_regression(Xid,yid)
 -------------------------------------------------------------------------
 INPUT
 -------------------------------------------------------------------------
 Xid: matrix containing the regressors. Each row is a datapoint.
 yid: column vector containing the output datapoints.
 -------------------------------------------------------------------------
 OUTPUT
 -------------------------------------------------------------------------
 idmodes: structure containing all information on the identified models.
   idmodes.par{i}: is the PVs of the i-th mode.
   idmodes.regions(i): is the region of the i-th mode. Regions are
   subsets of idpar.Regressor_set.
   idmodes.cov{i}; is the covariance of the PV of the i-th mode.
   idmodes.Regressor_set: automatically computed polytope defining the
   regressor set. This field is present only if idpar.Regressor_set is
   empty or nonexistent.
   idmodes.s: meaningful number of modes estimated during regression (it
   might differ from idpar.s).
   idmodes.regions_sim(i): is the region for simulating the i-th mode.
   These regions are subsets of idpar.Regressor_set_sim and are defined
   only if idpar.Regressor_set_sim is defined.
   idmodes.stat_reattr: fraction of points reattribted to modes, if
   reattribution has been performed.
   idmodes.clust_valid: structure containing information about the
   clustering results.
   idmodes.pattern_rec_valid: structure containing information about the
   pattern recognition results.
   idmodes.Weight_primal: weights used in creating LDs (usually it is a
   vector of 1's)
   idmodes.adjacences: each row is a pair (i,j), i<j indicating that the
   regions i and j are adjacent The constraint i<j avoids storing both
   pairs (i,j) and (j,i).
 F: structure containing information about the mode datasets (the
 classified datapoints that are also inliers, i.e. not discarded during
 regression).
   F.X{i}: matrix of regressors assigned to the i-th mode dataset.
   F.y: cell array: F.y{i} vector of outputs assigned to the i-th mode
   dataset.
   F.pos{i}: indexes of the points assigned to the i-th mode dataset.
   F.pos{i}(1)=5 means that Xid(5,:) and yid(5) are the first points
   composing the i-th mode dataset.
 xi: structure containing information about the xi-points (they are either
 FVs or LPVs).
    xi.points{i}: xi-point based on the i-th LDs.
   xi.IR{i}: INVERSE of the covariance of the i-th xi-point.
   xi.weights{i}: scalar confidence measure of the i-th feature vector.
 LDs: structure containing information about local datasets (LDs)
 and local models
    LDs.X{i}:  matrix of regressors belonging to the i-th local dataset
    (each row is a point).
   LDs.y{i}: vector of outputs belonging to the i-th local dataset.
   LDs.pos{i}: vector of indexes of datapoints in the i-th local
   dataset, e.g. Xid(LDs.pos{i}(1),:) is the first regressor in the i-th
   LD.
   LDs.weights{i} weight associated to the i-th datapoint used in
   weighted LS for computing mode PVs.
   LDs.meanX{i} average of regressors in the i-th local dataset.
   LDs.models{i} parameters of the i-th local model.
   LDs.models_var{i} INVERSE variance of the i-th local model.
   LDs.X_ivar{i} INVERSE of the variance of the the regressors in the
   i-th LD.
 inliers: structure containing information on the inliers
    inliers.pos(j): index of the j-th inlier in Xid and yid
    (i.e.Xid(inliers.pos(j),:) and yid(inliers.pos(j)) are the j-th
    inliers).
   inliers.class(j): classification of the j-th inlier.
CROSS-REFERENCE INFORMATION
This function calls:
hit_attribute_outliers HIT_ATTRIBUTE_OUTLIERS Attribute outliers to the modes and update inliers accordingly
hit_check_inliers HIT_CHECK_INLIERS Remove modes, if necessary, from a list of inliers
hit_compute_cont_modes HIT_COMPUTE_CONT_MODES Estimate the mode PVs in continuous PWA models
hit_compute_disc_modes HIT_COMPUTE_DISC_MODES Estimate the mode PVs in discontinuous PWA models
hit_create_LDs HIT_CREATE_LDS Create Local Datasets (LDs)
hit_error HIT_ERROR: Initializes the HIT toolbox if not already done
hit_plotpar_check HIT_PLOTPAR_CHECK Check if the cell array of fields lfields in plotpar is well defined
hit_reattribute_suspected HIT_REATTRIBUTE_SUSPECTED Re-attribute inliers suspected to be mixed to the modes
This function is called by:
hit_estimate_cs HIT_ESTIMATE_CS Estimate the best mode number and/or the best size of LDs within a given range