Description of hit_plot_idmodes
Home > hit > plotting > hit_plot_idmodes.m
hit_plot_idmodes
PURPOSE
HIT_PLOT_IDMODES Plot the identified PWA model if the domain is 1D or 2D.
SYNOPSIS
function hit_plot_idmodes(X_or, y_or,inliers,idmodes,fig,flag_bigregionsim)
DESCRIPTION
HIT_PLOT_IDMODES Plot the identified PWA model if the domain is 1D or 2D.
 -------------------------------------------------------------------------
 DESCRIPTION
 -------------------------------------------------------------------------
 hit_plot_idmodes(X_or, y_or,inliers,idmodes,fig,flag_bigregionsim)
 -------------------------------------------------------------------------
 INPUT
 -------------------------------------------------------------------------
 X_or: matrix containing the regressors. Each row is a datapoint.
 y_or: column vector containing the output datapoints.
 inliers: structure containing information on the inliers. Type 'help
 hit_regression' for a description of the fields.
 idmodes: structure containing information on the identified PWA model.
 Type 'help hit_regression' for a description of the fields.
 fig: # of the figure displaying the plot.
 flag_bigregionsim (optional, default=0): If =1, the modes over the
 regressor set for simulation (idpar.Regressor_set_sim) are plot.
 -------------------------------------------------------------------------
 OUTPUT
 -------------------------------------------------------------------------
 (none)
CROSS-REFERENCE INFORMATION
This function calls:
hit_plot_regions3d HIT_PLOT_REGIONS3D Plot the regions of a PWA model with 2D domain.
hit_pwa_plot1d HIT_PWA_PLOT1D Plot a PWA function with 1D domain.
hit_pwa_plot2d HIT_PWA_PLOT2D Plot a PWA function with 2D domain.
This function is called by: