% filename: verify_boundingCircle.m
% Purpose:  verifies if each point of an edge giving by vertices v1 and v2 are inside a circle generated by the position center
% Input:
% - v1 - array with x and y coordinates of vertice v1
% - v2 - array with x and y coordinates of vertice v2
% - center - array with x and y coordinates of the center position
% - r - the circle radius 
% Output:
% boundingSet - array with 1 to vertices inside the circle and -1 for outisde 
% e.g. bondingSet=[1,-1] vertice v1 is inside the circle and v2 is not. 


function boundingSet = verify_boundingCircle(v1,v2,center,r)

boundingSet=ones(1,2); %set every point as inside '1'

if pdist([v1; center],'euclidean') > r
   boundingSet(1,1)=-1;
end
if pdist([v2; center],'euclidean') > r
   boundingSet(1,2)=-1;
end
   