Description of nobias
Home > hit > pattern_rec > nobias.m
nobias
PURPOSE
NOBIAS Returns true if SVM kernel has no implicit bias
SYNOPSIS
function nb = nobias(ker)
DESCRIPTION
NOBIAS Returns true if SVM kernel has no implicit bias
  Usage: nb = nobias(ker)
  Parameters: ker - kernel type
  Author: Steve Gunn (srg@ecs.soton.ac.uk)
CROSS-REFERENCE INFORMATION
This function calls:
nobias NOBIAS Returns true if SVM kernel has no implicit bias
This function is called by:
nobias NOBIAS Returns true if SVM kernel has no implicit bias
svc SVC Support Vector Classification