Description of svc
Home > hit > pattern_rec > svc.m
svc
PURPOSE
SVC Support Vector Classification
SYNOPSIS
function [nsv, alpha, b0] = svc(X,Y,ker,C,solver)
DESCRIPTION
  SVC Support Vector Classification
  Usage: [nsv alpha bias] = svc(X,Y,ker,C)
  Parameters: X      - Training inputs
              Y      - Training targets
              ker    - kernel function
              C      - upper bound (non-separable case)
              nsv    - number of support vectors
              alpha  - Lagrange Multipliers
              b0     - bias term
  Author: Steve Gunn (srg@ecs.soton.ac.uk), modified by Giancarlo
  Ferrari-Trecate for using the solver for QPs in MPT
CROSS-REFERENCE INFORMATION
This function calls:
nobias NOBIAS Returns true if SVM kernel has no implicit bias
svc SVC Support Vector Classification
svkernel SVKERNEL Kernel for Support Vector Methods
svtol SVTOL Tolerance for Support Vectors
This function is called by:
hit_prec_SVC HIT_PREC_SVC Compute mode regions through Support Vector Classification (SVC)
svc SVC Support Vector Classification