Description of svkernel
Home > hit > pattern_rec > svkernel.m
svkernel
PURPOSE
SVKERNEL Kernel for Support Vector Methods
SYNOPSIS
function k = svkernel(ker,u,v)
DESCRIPTION
SVKERNEL Kernel for Support Vector Methods
  Usage: k = svkernel(ker,u,v)
  Parameters: ker - kernel type
              u,v - kernel arguments
  Values for ker: 'linear'  -
                  'poly'    - p1 is degree of polynomial
                  'rbf'     - p1 is width of rbfs (sigma)
                  'sigmoid' - p1 is scale, p2 is offset
                  'spline'  -
                  'bspline' - p1 is degree of bspline
                  'fourier' - p1 is degree
                  'erfb'    - p1 is width of rbfs (sigma)
                  'anova'   - p1 is max order of terms
  Author: Steve Gunn (srg@ecs.soton.ac.uk)
CROSS-REFERENCE INFORMATION
This function calls:
svkernel SVKERNEL Kernel for Support Vector Methods
This function is called by:
svc SVC Support Vector Classification
svkernel SVKERNEL Kernel for Support Vector Methods