Description of svtol
Home > hit > pattern_rec > svtol.m
svtol
PURPOSE
SVTOL Tolerance for Support Vectors
SYNOPSIS
function tol = svtol(C)
DESCRIPTION
SVTOL Tolerance for Support Vectors
  Usage: tol = svtol(C)
  Parameters: C      - upper bound
  Author: Steve Gunn (srg@ecs.soton.ac.uk)
CROSS-REFERENCE INFORMATION
This function calls:
svtol SVTOL Tolerance for Support Vectors
This function is called by:
svc SVC Support Vector Classification
svtol SVTOL Tolerance for Support Vectors