Description of chromatic_poly
Home > matgraph > @graph > chromatic_poly.m
chromatic_poly
PURPOSE
chromatic_poly(g) --- find the chromatic polynomial of g
SYNOPSIS
function p = chromatic_poly(g)
DESCRIPTION
 chromatic_poly(g) --- find the chromatic polynomial of g
 Warning: This algorithm is extremely slow and unusable except for very
 small graphs.
CROSS-REFERENCE INFORMATION
This function calls:
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
contract contract(g,u,v) --- contract v into u
copy copy(g,h) --- overwrite g with a copy of h
delete delete --- delete vertices or edges from a graph
edges edges(g) --- list the edges in g as a 2-column matrix
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
ne ne(g) --- number of edges in g or ne(g,h) --- check for inequality
nv nv(g) --- number of vertices in g
This function is called by:
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
SOURCE CODE
function p = chromatic_poly(g)
% chromatic_poly(g) --- find the chromatic polynomial of g
% Warning: This algorithm is extremely slow and unusable except for very
% small graphs.
n = nv(g);
m = ne(g);
if m==0
    p = zeros(1,n+1);
    p(1) = 1;
    return
end
elist = edges(g);
u = elist(1,1);
v = elist(1,2);
h = graph;
copy(h,g);
delete(h,u,v);
p1 = chromatic_poly(h);
contract(h,u,v);
p2 = chromatic_poly(h);
p = p1 - [0,p2];
free(h);