Description of edges
Home > matgraph > @graph > edges.m
edges
PURPOSE
edges(g) --- list the edges in g as a 2-column matrix
SYNOPSIS
function elist = edges(g)
DESCRIPTION
 edges(g) --- list the edges in g as a 2-column matrix
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
dot dot(g,filename) --- save graph for use by graphviz.
graffle graffle(g, filename, width, rad) --- write graph in OmniGraffle format
incidence_matrix incidence_matrix(g) --- return the vertex/edge incidence matrix.
line_graph line_graph(g,h) --- set g to be the line graph of h
prufer prufer --- convert a tree to/from its Prufer code
save save(g,filename) --- save a graph to disk
sgf sgf --- simple graph format: a 2-column matrix representation
SOURCE CODE
function elist = edges(g)
% edges(g) --- list the edges in g as a 2-column matrix
global GRAPH_MAGIC
[i,j] = find(triu(GRAPH_MAGIC.graphs{g.idx}.array));
elist = [i,j];