Description of incidence_matrix
Home > matgraph > @graph > incidence_matrix.m
incidence_matrix
PURPOSE
incidence_matrix(g) --- return the vertex/edge incidence matrix.
SYNOPSIS
function M = incidence_matrix(g)
DESCRIPTION
 incidence_matrix(g) --- return the vertex/edge incidence matrix.
 We return M an nv-by-ne matrix whose ij entry is 1 if vertex i is an
 end point of edge j.
CROSS-REFERENCE INFORMATION
This function calls:
edges edges(g) --- list the edges in g as a 2-column matrix
size size(g) --- returns [nv,ne] for the graph
This function is called by:
alpha [a,S] = alpha(g) --- indepencence number
SOURCE CODE
function M = incidence_matrix(g)
% incidence_matrix(g) --- return the vertex/edge incidence matrix.
% We return M an nv-by-ne matrix whose ij entry is 1 if vertex i is an
% end point of edge j.
[n,m] = size(g);
e = edges(g);
M = logical(zeros(n,m));
for k=1:m
    a = e(k,1);
    b = e(k,2);
    M(a,k)=1;
    M(b,k)=1;
end